import { app, BrowserWindow, ipcMain } from 'electron'
import { ProgressItemOptions, ProgressWindow } from '../../../dist/cjs'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit()
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    acceptFirstMouse: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  })

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

/**
 *  timer with progress and complete callbacks,
 * returns cancel, pause, and resume functions
 * @param time - time in ms
 * @param progress - progress callback
 * @param complete - complete callback
 */
function timerWithProgress(
  time: number,
  progress: (progress: number) => void,
  complete: () => void
) {
  let startTime = Date.now()
  let pausedTime = 0
  let pausedStartTime = 0
  let pausedEndTime = 0
  let cancel = false
  let pause = false
  let resume = false
  let interval: NodeJS.Timeout

  function tick() {
    if (cancel) {
      clearInterval(interval)
      return
    }
    if (pause) {
      pausedStartTime = Date.now()
      clearInterval(interval)
      return
    }
    if (resume) {
      pausedEndTime = Date.now()
      pausedTime += pausedEndTime - pausedStartTime
      startTime += pausedEndTime - pausedStartTime
      resume = false
      interval = setInterval(tick, 100)
      return
    }
    const elapsed = Date.now() - startTime - pausedTime
    const progressPercent = Math.min(100, Math.max(0, (elapsed / time) * 100))
    progress(progressPercent)
    if (elapsed >= time) {
      clearInterval(interval)
      complete()
    }
  }

  interval = setInterval(tick, 100)

  return {
    cancel: () => {
      cancel = true
    },
    pause: () => {
      pause = true
    },
    resume: () => {
      resume = true
    },
  }
}

ipcMain.on(
  'add-progress-item',
  async (event, options: ProgressItemOptions, timer: { time: number }) => {
    const item = await ProgressWindow.addItem(options)
    const { cancel, pause, resume } = timerWithProgress(
      timer.time * 1000,
      (progress) => {
        item.setProgress(progress)
      },
      () => {
        if (!options.autoComplete) {
          item.setCompleted()
        }
      }
    )
    item.on('cancelled', () => {
      cancel()
    })
    item.on('pause', (shouldPause: boolean) => {
      if (shouldPause) {
        pause()
      } else {
        resume()
      }
    })
  }
)
